### ISSUE TITLE
Question about the Shapeformer article

### ISSUE THREAD

**Issue by felipeduuartee** [hexiangdong2020/BoTorch_MOBO_example#1]
Good morning!

I would like to know if you managed to reproduce the results for all the datasets from the Shapeformer article! She closed the issues, and I’m facing exactly the same problems as you, with accuracy identical to those that don’t match the results presented in her article!

Thank you for your attention!

**Comment by hexiangdong2020** [comment]
Good morning!
In reproducing her work, we found that her code had a test data leak. She used the test set as a validation set, which is not the case in CovnTrans. Below is the figure:
[cid:04f20532-c3a4-4112-b2b6-616e0a04d8c8]
I think you can react to the conference editor about this. Don't put your trust in this work.
Sincerely
________________________________
发件人: Felipe Duarte ***@***.***>
发送时间: 2024年11月27日 21:33
收件人: hexiangdong2020/BoTorch_MOBO_example ***@***.***>
抄送: Subscribed ***@***.***>
主题: [hexiangdong2020/BoTorch_MOBO_example] Question about the Shapeformer article (Issue #1)


Good morning!

I would like to know if you managed to reproduce the results for all the datasets from the Shapeformer article! She closed the issues, and I’m facing exactly the same problems as you, with accuracy identical to those that don’t match the results presented in her article!

Thank you for your attention!

―

**Comment by hexiangdong2020** [comment]
Good morning!
In reproducing her work, we found that her code had a test data leak. She used the test set as a validation set, which is not the case in CovnTrans. Below is the figure:
![image](https://github.com/user-attachments/assets/2a3e66c4-d346-4590-ab3f-a40335e85128)

I think you can react to the conference editor about this. Don't put your trust in this work.
Sincerely
